#page title
page_title                                :                                           # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1627081052                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : us                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :                                         # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : # assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Create your own well-balanced soap recipe.

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Galina Aleksandrova                                
your_link                                 : https://www.linkedin.com/in/galina-aleksandrova-a1b647238/                    
your_city                                 : Spain                               
email_address                             : galina.aleks1012@gmail.com
facebook_username                         :                                           
instagram_username                        : galexanrova
twitter_username                          : 
github_username                           : 2007riot
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Calculate your homemade soap recipe
    description                           : Saponification calculator that allows you to create natural homemade soap from lye and oils. 
    fontawesome_icon_name                 : calculator
    
  - title                                 : Great for beginners
    description                           : Create a well-balanced soap recipe, no matter if it’s your first soap or you are a professional soap maker.
    fontawesome_icon_name                 : face-smile-wink

  - title                                 : Over 100 oils to choose from
    description                           : Big list of oils and butters to choose from with its properties and fatty acids parametres. 
    fontawesome_icon_name                 : bottle-droplet

  - title                                 : And over 40 essential oils
    description                           : Add scent to your soap by adding essential oils and check its recommendation
    fontawesome_icon_name                 : spray-can-sparkles

  - title                                 : Tips and recommendation
    description                           : If you are new to making homemade soap read brief info and tips about soap making process.
    fontawesome_icon_name                 : block-question
  
  - title                                 : Save recipes to your device
    description                           : Save recipes and reach them anytime without an Internet connection.
    fontawesome_icon_name                 : box-archive

  - title                                 : #Smart App Banner
    description                           : #Display a smart app banner on iOS devices.
    fontawesome_icon_name                 : #arrow-alt-circle-down

  - title                                 : #Social Links
    description                           : #Easily add social media accounts and contact info in the footer via the _config.yml file. No HTML/CSS needed.
    fontawesome_icon_name                 : #link

  - title                                 : #FontAwesome Support
    description                           : #Pick custom Font Awesome icons for the feature list via the _config.yml file. No HTML/CSS needed.
    fontawesome_icon_name                 : #info-circle

  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/coverImage.png                  # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#11998E"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
